
skillMetadata:
  sections:
    - name: Input Ical - Url
      fields:
        - name: ical_url
          type: text
          label: Ical Url
          value: ""
          placeholder: demo prompt in the input box
    - name: Login 
      fields:
        - type: label
          label: Please enter your username and password
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
